# Use Python base image
FROM pytorch/pytorch:2.5.1-cuda11.8-cudnn9-runtime

# Set work directory
WORKDIR /api

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && python3 -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2');" \
    && python3 -c "import nltk; nltk.download('punkt_tab');"

# Expose FastAPI port
EXPOSE 8000

# Run with Uvicorn
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]