FROM python:3.12-slim

WORKDIR /platform

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN rm db/database.db && touch db/database.db

RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]