events {}

http {    

    # Max Body Size
    client_max_body_size 1024M;

    # Rate limiting zone: 5 requests per minute per IP
    limit_req_zone $binary_remote_addr zone=submit_limit:10m rate=5r/m;
    
    server {
        
        listen 80;

        # Timeout
        proxy_connect_timeout 1000s;
        proxy_send_timeout 1000s;
        proxy_read_timeout 1000s;
        client_body_timeout 1000s;
        send_timeout 1000s;

        # Redirect / to /exposed/
        location = / {
            return 302 /exposed/;
        }

        # Exposed API - NO rate limiting
        location /exposed/ {
            proxy_pass http://platform:8000/exposed/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Public API - NO rate limiting
        location /public/ {
            proxy_pass http://platform:8000/public/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Internal submit endpoint
        location /internal/submit {

            # Rate limitting
            limit_req zone=submit_limit burst=5 nodelay;
            limit_req_status 429;
            
            proxy_pass http://platform:8000/internal/submit;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Other internal endpoints - NO rate limiting
        location /internal/ {
            proxy_pass http://platform:8000/internal/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }


        location @rate_limit_json {
            default_type application/json;
            return 429 '{"error": "rate_limit_exceeded", "message": "Too many submissions. Please wait before trying again."}';
        }

    }
}